# Generated by Django 3.2.6 on 2021-08-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailypicks',
            options={'verbose_name': 'Daily Picks'},
        ),
    ]
