# Generated by Django 3.2.6 on 2021-08-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0002_alter_dailypicks_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailypicks',
            options={'verbose_name': 'Daily Pick', 'verbose_name_plural': 'Daily Picks'},
        ),
    ]
