# Generated by Django 3.2.6 on 2021-08-31 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0010_dailypicks_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypicks',
            name='title',
            field=models.CharField(default=datetime.date.today, max_length=20),
        ),
    ]
