# Generated by Django 3.2.6 on 2021-08-31 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0011_alter_dailypicks_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailypicks',
            name='title',
        ),
    ]
